name: simple_barcode_scanner
description: Scanner plugin for Barcode/QR code. Scan using flutter_barcode_scanner for mobile device and html5-qrcode for web and windows
version: 0.0.8
homepage: https://github.com/CodingWithTashi/simple_barcode_scanner
issue_tracker: https://github.com/CodingWithTashi/simple_barcode_scanner/issues

platforms:
  android:
  ios:
  web:
  windows:

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Flutter window webview
  webview_windows: ^0.2.2
  # Barcode scanner for android and ios
  flutter_barcode_scanner: ^2.0.0
  #Get assets path for window platform
  path: ^1.8.2
  #checking permissions
  permission_handler: ^11.0.1
  webview_flutter: ^4.4.1
  mobile_scanner: 5.0.0-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/simple_barcode_scanner/assets/barcode.html
    - packages/simple_barcode_scanner/assets/html5-qrcode.min.js
